name: Deploy Wiki to GitHub Pages

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' # Adjust the schedule as needed (this runs daily)
  push:
    paths:
      - '*.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Clone Wiki
      run: |
        git clone https://github.com/babsonnexus/stream-link-manager-for-channels.wiki.git wiki
        cd wiki
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"

    - name: Convert Wiki to HTML
      run: |
        mkdir -p public
        cp -r wiki/* public/
        # Add any additional conversion steps if needed

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
