name: Deploy GitHub Pages

on:
  push:
    paths:
      - 'README.md'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install pandoc
      run: sudo apt-get update && sudo apt-get install -y pandoc

    - name: Create README.html from README.md
      run: pandoc README.md -o README.html

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: main
        publish_dir: ./
