name: Deploy Wiki to GitHub Pages

on:
  push:
    paths:
      - 'wiki/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    - name: Convert Wiki to HTML
      run: |
        mkdir -p public
        cp -r wiki/* public/
        # Add any additional conversion steps if needed

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
