name: Update GitHub Pages

on:
  push:
    paths:
      - 'README.md'  # Only trigger on changes to the README.md file

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build site
        run: |
          # Commands to build your site
          # e.g., jekyll build or any other static site generator command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public  # Adjust according to your site’s build output directory
